website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from .models import IDCard

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if user:
            # if check_password_hash(user.password, password): #เปรียบเทียบแบบเข้ารหัส
            if user.password == password:
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('auth.id_list'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist or Sign up contact Admin.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated and current_user.role == 'admin':
        if request.method == 'POST':
            username = request.form.get('username')
            name = request.form.get('Name')
            password1 = request.form.get('password1')
            password2 = request.form.get('password2')
            role = request.form.get('role')
            
            user = User.query.filter_by(username=username).first()
            if user:
                flash('Username already exists.', category='error')
            elif len(username) < 4:
                flash('Username must be greater than 3 characters.', category='error')
            elif len(name) < 2:
                flash('Name must be greater than 1 character.', category='error')
            elif password1 != password2:
                flash('Passwords don\'t match.', category='error')
            elif len(password1) < 7:
                flash('Password must be at least 7 characters.', category='error')
            elif role not in ['admin', 'user']:  # เพิ่มเงื่อนไขในการตรวจสอบ role
                flash('Role must be: admin, user', category='error')
            else:
                # new_user = User(username=username, name=name, password=generate_password_hash(password1, method='pbkdf2:sha256'), role=role) #เก็บรหัสแบบปลอดภัยแต่ดูไม่ได้
                new_user = User(username=username, name=name, password=password1, role=role)
                db.session.add(new_user)
                db.session.commit()
                login_user(current_user, remember=True)
                flash('Account created!', category='success')
                return redirect(url_for('views.home'))
    else:
        flash('You are not authorized to access this page.', category='error')
        return redirect(url_for('auth.login'))
    
    return render_template("sign_up.html", user=current_user)


@auth.route('/user-list')
def user_list():
    if current_user.is_authenticated and current_user.role == 'admin':
        users = User.query.all()
        return render_template('user_list.html', users=users, user=current_user)  # เพิ่มตัวแปร user=current_user
    else:
        # ถ้าไม่ใช่ admin ให้ทำการ redirect หรือแสดงข้อความผิดพลาด
        return "You do not have access to view this page."



@auth.route('/user-edit/<int:user_id>', methods=['GET', 'POST'])
def user_edit(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.is_authenticated and current_user.role == 'admin':
        if request.method == 'POST':
            name = request.form.get('name')
            password = request.form.get('password')

            if len(name) < 2:
                flash('Name must be greater than 1 character.', category='error')
            elif len(password) > 0 and len(password) < 7:
                flash('Password must be at least 7 characters.', category='error')
            else:
                user.name = name
                if len(password) > 0:
                    user.password = password

                db.session.commit()
                flash('User updated successfully!', category='success')
                return redirect(url_for('auth.user_list'))
        
        return render_template('user_edit.html', user=user)
    else:
        flash('You are not authorized to access this page.', category='error')
        return redirect(url_for('auth.login'))


@auth.route('/user-delete/<int:user_id>')
def user_delete(user_id):
    if current_user.is_authenticated and current_user.role == 'admin':
        user = User.query.get(user_id)
        if not user:
            return "User not found"

        if user.id == 1:
            return "Cannot delete user with ID 1"

        db.session.delete(user)
        db.session.commit()
        return redirect(url_for('auth.user_list'))
    else:
        return "You do not have access to view this page."
    

@auth.route('/')
def id_list():
        id_cards = IDCard.query.all()
        return render_template('id_list.html', id_cards=id_cards, user=current_user)

def delete_id_card(id_number):
    try:
        # Find the ID card by id_number
        id_card = IDCard.query.get(id_number)
        
        if id_card:
            # Delete the ID card
            db.session.delete(id_card)
            db.session.commit()
            return True, "ID Card deleted successfully"
        else:
            return False, "ID Card not found"
    except Exception as e:
        return False, str(e)

# Route to handle ID card deletion
@auth.route('/delete_id_card', methods=['POST'])
def delete_id_card_route():
    id_number = request.form.get('id_number')
    success, message = delete_id_card(id_number)
    return {'success': success, 'message': message}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Home</a>

            {% if user.role == 'admin' %}
              <a class="nav-item nav-link" id="user" href="/user-list">User</a>
            {% endif %}

            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>

          {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}

        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock %}

website/templates/id_add.html
{% extends "base.html" %} 
{% block title %}Home{% endblock %} 
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Card Reader</title>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"> -->
    <style>
        body {
            background-color: #f8f9fa;
            /* font-family: Arial, sans-serif; */
        }
        .container {
            max-width: 750px;
            margin-top: 50px;
        }
        .card {
            position: relative;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .photo-image {
            position: absolute;
            top: 0;
            right: 70px;
            max-width: 100px;
            margin-top: 20px; /* Adjust this value as needed */
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center mb-4">Card Reader</h2>
        
        <div class="text-center mb-3">
            <button class="btn btn-primary" onclick="getData()">Get Card Data</button>
        </div>
        <div id="saveButton" class="mb-2" style="display: none;" align="right">
            <button class="btn btn-success mt-3" onclick="saveData()">Save Data</button>
        </div>
        
        <div id="cardData" class="card">
            <div id="status" class="mb-2"></div>
            <div id="message" class="mb-2"></div>
            <div id="idNumber" class="mb-2"></div>
            <div id="thaiName" class="mb-2"></div>
            <div id="engName" class="mb-2"></div>
            <div id="gender" class="mb-2"></div>
            <div id="dob" class="mb-2"></div>
            <div id="age" class="mb-2"></div>
            <div id="religion" class="mb-2"></div>
            <div id="address" class="mb-2"></div>
            <div id="issuer" class="mb-2"></div>
            <div id="doi" class="mb-2"></div>
            <div id="doe" class="mb-2"></div>
            <div id="photo" class="photo-image">
            
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        function getData() {
            axios.get('/get_data')
                .then(function(response) {
                    const status = response.data['Status'];
                    document.getElementById('status').innerHTML = "<strong>Status:</strong> " + status;

                    if (status === 200) {
                        document.getElementById('saveButton').style.display = 'block';
                    } else {
                        document.getElementById('saveButton').style.display = 'none';
                    }

                    document.getElementById('message').innerHTML = "<strong>Message:</strong> " + response.data['Message'];
                    document.getElementById('idNumber').innerHTML = "<strong>ID Number:</strong> " + response.data['ID Number'];
                    document.getElementById('thaiName').innerHTML = "<strong>Thai Name:</strong> " + response.data['Thai Name'];
                    document.getElementById('engName').innerHTML = "<strong>English Name:</strong> " + response.data['English Name'];
                    document.getElementById('gender').innerHTML = "<strong>Gender:</strong> " + response.data['Gender'];
                    document.getElementById('dob').innerHTML = "<strong>Date of Birth:</strong> " + response.data['Date of Birth'];
                    document.getElementById('age').innerHTML = "<strong>Age:</strong> " + response.data['Age'];
                    document.getElementById('religion').innerHTML = "<strong>Religion:</strong> " + response.data['Religion'];
                    document.getElementById('address').innerHTML = "<strong>Address:</strong> " + response.data['Address'];
                    document.getElementById('issuer').innerHTML = "<strong>Issuer:</strong> " + response.data['Issuer'];
                    document.getElementById('doi').innerHTML = "<strong>Date of Issue:</strong> " + response.data['Date of Issue'];
                    document.getElementById('doe').innerHTML = "<strong>Date of Expiry:</strong> " + response.data['Date of Expiry'];

                    const photoBase64 = response.data['Photo(base64)'];
                    const photoElement = document.getElementById('photo');
                    photoElement.innerHTML = `<img src="data:image/png;base64, ${photoBase64}" alt="Photo" />`;
                })
                .catch(function(error) {
                    console.error('Error fetching data:', error);
                });
        }


        function saveData() {
            axios.get('/get_data')
                .then(function(response) {
                    const card_data = response.data;
                    axios.post('/idcard-add', card_data)
                        .then(function(response) {
                            console.log('Data saved successfully:', response);
                            alert('Data saved successfully!');
                        })
                        .catch(function(error) {
                            console.error('Error saving data:', error);
                        });
                })
                .catch(function(error) {
                    console.error('Error fetching data:', error);
                });
    }
</script>
</body>
</html>
{% endblock %}

website/templates/id_list.html
{% extends "base.html" %}
{% block title %}ID Card List{% endblock %}
{% block content %}
<div class="container">
    <br>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>ID Card</h1>
        <a href="{{ url_for('views.home') }}" class="btn btn-success">Add</a>
      </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID Number</th>
                <th>Thai Name</th>
                <th>English Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for card in id_cards %}
            <tr>
                <td>{{ card.id_number }}</td>
                <td>{{ card.thai_name }}</td>
                <td>{{ card.english_name }}</td>
                <td><button onclick="showFullView('{{ card.id_number }}')"class="btn btn-info">View</button>
                <button onclick="deleteCard('{{ card.id_number }}')"class="btn btn-danger">Delete</button></td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Popup Content -->
<div id="popup" style="display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: white; padding: 20px; border: 1px solid #ccc; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); width: 40%; height: 95%; overflow: auto;">
    <button onclick="closePopup()" style="position: absolute; top: 10px; right: 10px;"class="btn btn-dark">X</button>
    <div id="popupContent"></div>
</div>

<script>
    const id_cards = [{% for card in id_cards %}
        {
            photo_base64: '{{ card.photo_base64 }}',
            id_number: '{{ card.id_number }}',
            thai_name: '{{ card.thai_name }}',
            english_name: '{{ card.english_name }}',
            gender: '{{ card.gender }}',
            date_of_birth: '{{ card.date_of_birth }}',
            age: '{{ card.age }}',
            religion: '{{ card.religion }}',
            address: '{{ card.address }}',
            issuer: '{{ card.issuer }}',
            date_of_issue: '{{ card.date_of_issue }}',
            date_of_expiry: '{{ card.date_of_expiry }}',
        },
    {% endfor %}];

    function showFullView(idNumber) {
        const card = findCardByIdNumber(idNumber);
        const popupContent = `
            <img src="data:image/png;base64, ${card.photo_base64}" style="max-width: 100%; height: auto; display: block; margin: 0 auto;" alt="Photo" />
            
            <p>ID Number: ${card.id_number}</p>
            <p>Thai Name: ${card.thai_name}</p>
            <p>English Name: ${card.english_name}</p>
            <p>Gender: ${card.gender}</p>
            <p>Date of Birth: ${card.date_of_birth}</p>
            <p>Age: ${card.age}</p>
            <p>Religion: ${card.religion}</p>
            <p>Address: ${card.address}</p>
            <p>Issuer: ${card.issuer}</p>
            <p>Date of Issue: ${card.date_of_issue}</p>
            <p>Date of Expiry: ${card.date_of_expiry}</p>
            <button onclick="copyBase64('${card.photo_base64}')" class="btn btn-warning">Photo(Base64)</button>
            <!-- เพิ่มข้อมูลเพิ่มเติมตามต้องการ -->
        `;
        document.getElementById('popupContent').innerHTML = popupContent;
        document.getElementById('popup').style.display = 'block';
    }

    function copyBase64(base64Data) {
        const textArea = document.createElement('textarea');
        textArea.value = base64Data;
        document.body.appendChild(textArea);
        textArea.select();
        textArea.setSelectionRange(0, 99999);
        document.execCommand('copy');
        document.body.removeChild(textArea);
        alert('Photo(Base64) copied to clipboard!');
    }
    function closePopup() {
        document.getElementById('popup').style.display = 'none';
    }

    function findCardByIdNumber(idNumber) {
        return id_cards.find(card => card.id_number === idNumber);
    }
    function deleteCard(idNumber) {
        if (confirm('Are you sure you want to delete this ID card?')) {
            fetch('/delete_id_card', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: `id_number=${idNumber}`,
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert(data.message);
                    window.location.reload();
                    // Refresh the page or update the ID card list after successful deletion
                    // For example: location.reload();
                } else {
                    alert('Failed to delete ID card');
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred while deleting the ID card');
            });
        }
    }

</script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="username"><U></U>Username</label>
    <input
      type="username"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="Name">Name</label>
    <input
      type="text"
      class="form-control"
      id="Name"
      name="Name"
      placeholder="Enter Name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <div class="form-group">
    <label for="role">Role (admin/user)</label>
    <input
      type="text"
      class="form-control"
      id="role"
      name="role"
      placeholder="Enter role (admin/user)"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/user_edit.html
{% extends "base.html" %}
{% block title %}Edit User{% endblock %}
{% block content %}
  <h1>Edit User</h1>
  <form method="POST" action="{{ url_for('auth.user_edit', user_id=user.id) }}">
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" readonly>
    </div>
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ user.name }}">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Enter new password">
    </div>
    <div class="form-group">
      <label for="role">Role</label>
      <input type="text" class="form-control" id="role" name="role" value="{{ user.role }}" readonly>
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>
{% endblock %}

website/templates/user_list.html
{% extends "base.html" %}
{% block title %}User List{% endblock %}
{% block content %}
  <br>
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1>User List</h1>
    {% if current_user.is_authenticated and current_user.role == 'admin' %}
      <a href="{{ url_for('auth.sign_up') }}" class="btn btn-success">Add</a>
    {% endif %}
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Name</th>
        <th scope="col">Password</th>
        <th scope="col">Role</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <th scope="row">{{ user.id }}</th>
        <td>{{ user.username }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.password }}</td>
        <td>{{ user.role }}</td>
        <td>
            <a href="{{ url_for('auth.user_edit', user_id=user.id) }}" class="btn btn-primary">Edit</a>

          {% if user.id != 1 %}
            <a href="{{ url_for('auth.user_delete', user_id=user.id) }}" class="btn btn-danger">Delete</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}